spring:
  application:
    name: spring-smoketest
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
metadataserver:
  hostname: metadataserver.hyrulelab.com